controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_informations:
    path: /mes-informations
    controller: App\Controller\UserController::informations

user_update_informations:
    path: /update-informations
    controller: App\Controller\UserController::updateInformations
    methods: [POST]

user_update_password:
    path: /update-password
    controller: App\Controller\UserController::updatePassword
    methods: [POST]

api_login_check:
    path: /api/login_check
    methods: [POST]

ovoko_import_parts:
    path: /api/ovoko/import-parts
    controller: App\Controller\OvokoController::importParts
    methods: [POST]

api_callback:
    path: /api/callback
    controller: App\Controller\CallbackController::handleCallback
    methods: [POST]