services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service OpistoDataFetcher
    App\Service\OpistoDataFetcher:
        arguments:
            $client: '@http_client'
            $authService: '@App\Service\AuthenticationService'
            $apiUrl: '%env(AUTH_URL_API)%' # Injection de la variable d'environnement

    # Service AuthenticationService (déjà défini correctement)
    App\Service\AuthenticationService:
        arguments:
            $client: '@http_client'
            $cache: '@cache.app'

    # Autres services explicites
    App\Service\SiretVerificationService:
        arguments:
            $httpClient: '@http_client'

    App\Twig\AppExtension:
        tags: ['twig.extension']

    App\Form\DeliveryAdressType:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Form\BillingAdressType:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
